#基于暗示(Hint)的数据分片---强制路由演示
spring:
  shardingsphere:
    datasource:
      ds0:
        password: root
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ds0
        username: root
      ds1:
        password: root
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ds1
        username: root
      names: ds0,ds1
    sharding:
      binding-tables: t_order,t_order_item
      tables:
        t_order_item:
          actualDataNodes: ds${0..1}.t_order_item${0..1}
        t_order:
          tableStrategy:
            hint:
              algorithm-class-name: org.yaukie.demo.sharding.AutoHintShardingAlgorithm
          keyGenerator:
            column: order_id
            type: SNOWFLAKE
            props:
              worker:
                id: order_id
          actualDataNodes: ds${0..1}.t_order${0..1}
          databaseStrategy:
            hint:
              algorithm-class-name: org.yaukie.demo.sharding.AutoHintShardingAlgorithm
      default-database-strategy:
        inline:
          sharding-column: user_id
          algorithm-expression: ds${user_id % 2}
    props:
      sql:
        show: true