#配置服务器
server:
  port: 8009
  servlet:
    path: /sharding
  #配置数据源
spring:
  application:
    name: sharding-jdbc-demo
  profiles:
    include: hint
    active: dev #当前用来控制日志不同环境启用不用作用
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/test?useUniCode=true&characterEncoding=UTF-8
#    username: root
#    password: root
#扫描mapper配置
mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath*:mapper/*.xml
  #自定义日志
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
logging:
    config: classpath:logback-spring.xml
    path: E:/maven/sharding-jdbc-demo/sharding-jdbc-test/logs

