package org.yaukie.demo.autocode.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TEncryptOrderExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_encrypt_order
     *
     * @mbg.generated Mon Mar 30 09:45:06 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_encrypt_order
     *
     * @mbg.generated Mon Mar 30 09:45:06 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_encrypt_order
     *
     * @mbg.generated Mon Mar 30 09:45:06 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_encrypt_order
     *
     * @mbg.generated Mon Mar 30 09:45:06 CST 2020
     */
    public TEncryptOrderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_encrypt_order
     *
     * @mbg.generated Mon Mar 30 09:45:06 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_encrypt_order
     *
     * @mbg.generated Mon Mar 30 09:45:06 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_encrypt_order
     *
     * @mbg.generated Mon Mar 30 09:45:06 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_encrypt_order
     *
     * @mbg.generated Mon Mar 30 09:45:06 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_encrypt_order
     *
     * @mbg.generated Mon Mar 30 09:45:06 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_encrypt_order
     *
     * @mbg.generated Mon Mar 30 09:45:06 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_encrypt_order
     *
     * @mbg.generated Mon Mar 30 09:45:06 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_encrypt_order
     *
     * @mbg.generated Mon Mar 30 09:45:06 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_encrypt_order
     *
     * @mbg.generated Mon Mar 30 09:45:06 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_encrypt_order
     *
     * @mbg.generated Mon Mar 30 09:45:06 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_encrypt_order
     *
     * @mbg.generated Mon Mar 30 09:45:06 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserDecryptIsNull() {
            addCriterion("user_decrypt is null");
            return (Criteria) this;
        }

        public Criteria andUserDecryptIsNotNull() {
            addCriterion("user_decrypt is not null");
            return (Criteria) this;
        }

        public Criteria andUserDecryptEqualTo(String value) {
            addCriterion("user_decrypt =", value, "userDecrypt");
            return (Criteria) this;
        }

        public Criteria andUserDecryptNotEqualTo(String value) {
            addCriterion("user_decrypt <>", value, "userDecrypt");
            return (Criteria) this;
        }

        public Criteria andUserDecryptGreaterThan(String value) {
            addCriterion("user_decrypt >", value, "userDecrypt");
            return (Criteria) this;
        }

        public Criteria andUserDecryptGreaterThanOrEqualTo(String value) {
            addCriterion("user_decrypt >=", value, "userDecrypt");
            return (Criteria) this;
        }

        public Criteria andUserDecryptLessThan(String value) {
            addCriterion("user_decrypt <", value, "userDecrypt");
            return (Criteria) this;
        }

        public Criteria andUserDecryptLessThanOrEqualTo(String value) {
            addCriterion("user_decrypt <=", value, "userDecrypt");
            return (Criteria) this;
        }

        public Criteria andUserDecryptLike(String value) {
            addCriterion("user_decrypt like", value, "userDecrypt");
            return (Criteria) this;
        }

        public Criteria andUserDecryptNotLike(String value) {
            addCriterion("user_decrypt not like", value, "userDecrypt");
            return (Criteria) this;
        }

        public Criteria andUserDecryptIn(List<String> values) {
            addCriterion("user_decrypt in", values, "userDecrypt");
            return (Criteria) this;
        }

        public Criteria andUserDecryptNotIn(List<String> values) {
            addCriterion("user_decrypt not in", values, "userDecrypt");
            return (Criteria) this;
        }

        public Criteria andUserDecryptBetween(String value1, String value2) {
            addCriterion("user_decrypt between", value1, value2, "userDecrypt");
            return (Criteria) this;
        }

        public Criteria andUserDecryptNotBetween(String value1, String value2) {
            addCriterion("user_decrypt not between", value1, value2, "userDecrypt");
            return (Criteria) this;
        }

        public Criteria andUserEncryptIsNull() {
            addCriterion("user_encrypt is null");
            return (Criteria) this;
        }

        public Criteria andUserEncryptIsNotNull() {
            addCriterion("user_encrypt is not null");
            return (Criteria) this;
        }

        public Criteria andUserEncryptEqualTo(String value) {
            addCriterion("user_encrypt =", value, "userEncrypt");
            return (Criteria) this;
        }

        public Criteria andUserEncryptNotEqualTo(String value) {
            addCriterion("user_encrypt <>", value, "userEncrypt");
            return (Criteria) this;
        }

        public Criteria andUserEncryptGreaterThan(String value) {
            addCriterion("user_encrypt >", value, "userEncrypt");
            return (Criteria) this;
        }

        public Criteria andUserEncryptGreaterThanOrEqualTo(String value) {
            addCriterion("user_encrypt >=", value, "userEncrypt");
            return (Criteria) this;
        }

        public Criteria andUserEncryptLessThan(String value) {
            addCriterion("user_encrypt <", value, "userEncrypt");
            return (Criteria) this;
        }

        public Criteria andUserEncryptLessThanOrEqualTo(String value) {
            addCriterion("user_encrypt <=", value, "userEncrypt");
            return (Criteria) this;
        }

        public Criteria andUserEncryptLike(String value) {
            addCriterion("user_encrypt like", value, "userEncrypt");
            return (Criteria) this;
        }

        public Criteria andUserEncryptNotLike(String value) {
            addCriterion("user_encrypt not like", value, "userEncrypt");
            return (Criteria) this;
        }

        public Criteria andUserEncryptIn(List<String> values) {
            addCriterion("user_encrypt in", values, "userEncrypt");
            return (Criteria) this;
        }

        public Criteria andUserEncryptNotIn(List<String> values) {
            addCriterion("user_encrypt not in", values, "userEncrypt");
            return (Criteria) this;
        }

        public Criteria andUserEncryptBetween(String value1, String value2) {
            addCriterion("user_encrypt between", value1, value2, "userEncrypt");
            return (Criteria) this;
        }

        public Criteria andUserEncryptNotBetween(String value1, String value2) {
            addCriterion("user_encrypt not between", value1, value2, "userEncrypt");
            return (Criteria) this;
        }

        public Criteria andUserAssistedIsNull() {
            addCriterion("user_assisted is null");
            return (Criteria) this;
        }

        public Criteria andUserAssistedIsNotNull() {
            addCriterion("user_assisted is not null");
            return (Criteria) this;
        }

        public Criteria andUserAssistedEqualTo(String value) {
            addCriterion("user_assisted =", value, "userAssisted");
            return (Criteria) this;
        }

        public Criteria andUserAssistedNotEqualTo(String value) {
            addCriterion("user_assisted <>", value, "userAssisted");
            return (Criteria) this;
        }

        public Criteria andUserAssistedGreaterThan(String value) {
            addCriterion("user_assisted >", value, "userAssisted");
            return (Criteria) this;
        }

        public Criteria andUserAssistedGreaterThanOrEqualTo(String value) {
            addCriterion("user_assisted >=", value, "userAssisted");
            return (Criteria) this;
        }

        public Criteria andUserAssistedLessThan(String value) {
            addCriterion("user_assisted <", value, "userAssisted");
            return (Criteria) this;
        }

        public Criteria andUserAssistedLessThanOrEqualTo(String value) {
            addCriterion("user_assisted <=", value, "userAssisted");
            return (Criteria) this;
        }

        public Criteria andUserAssistedLike(String value) {
            addCriterion("user_assisted like", value, "userAssisted");
            return (Criteria) this;
        }

        public Criteria andUserAssistedNotLike(String value) {
            addCriterion("user_assisted not like", value, "userAssisted");
            return (Criteria) this;
        }

        public Criteria andUserAssistedIn(List<String> values) {
            addCriterion("user_assisted in", values, "userAssisted");
            return (Criteria) this;
        }

        public Criteria andUserAssistedNotIn(List<String> values) {
            addCriterion("user_assisted not in", values, "userAssisted");
            return (Criteria) this;
        }

        public Criteria andUserAssistedBetween(String value1, String value2) {
            addCriterion("user_assisted between", value1, value2, "userAssisted");
            return (Criteria) this;
        }

        public Criteria andUserAssistedNotBetween(String value1, String value2) {
            addCriterion("user_assisted not between", value1, value2, "userAssisted");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNull() {
            addCriterion("created_time is null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNotNull() {
            addCriterion("created_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeEqualTo(Date value) {
            addCriterion("created_time =", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotEqualTo(Date value) {
            addCriterion("created_time <>", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThan(Date value) {
            addCriterion("created_time >", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("created_time >=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThan(Date value) {
            addCriterion("created_time <", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThanOrEqualTo(Date value) {
            addCriterion("created_time <=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIn(List<Date> values) {
            addCriterion("created_time in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotIn(List<Date> values) {
            addCriterion("created_time not in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeBetween(Date value1, Date value2) {
            addCriterion("created_time between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotBetween(Date value1, Date value2) {
            addCriterion("created_time not between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_encrypt_order
     *
     * @mbg.generated do_not_delete_during_merge Mon Mar 30 09:45:06 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_encrypt_order
     *
     * @mbg.generated Mon Mar 30 09:45:06 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}