package org.yaukie.demo.autocode.model;

import java.util.Date;

public class TEncryptOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_encrypt_order.id
     *
     * @mbg.generated Mon Mar 30 09:45:06 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_encrypt_order.user_id
     *
     * @mbg.generated Mon Mar 30 09:45:06 CST 2020
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_encrypt_order.user_decrypt
     *
     * @mbg.generated Mon Mar 30 09:45:06 CST 2020
     */
    private String userDecrypt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_encrypt_order.user_encrypt
     *
     * @mbg.generated Mon Mar 30 09:45:06 CST 2020
     */
    private String userEncrypt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_encrypt_order.user_assisted
     *
     * @mbg.generated Mon Mar 30 09:45:06 CST 2020
     */
    private String userAssisted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_encrypt_order.created_time
     *
     * @mbg.generated Mon Mar 30 09:45:06 CST 2020
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_encrypt_order.update_time
     *
     * @mbg.generated Mon Mar 30 09:45:06 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_encrypt_order.id
     *
     * @return the value of t_encrypt_order.id
     *
     * @mbg.generated Mon Mar 30 09:45:06 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_encrypt_order.id
     *
     * @param id the value for t_encrypt_order.id
     *
     * @mbg.generated Mon Mar 30 09:45:06 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_encrypt_order.user_id
     *
     * @return the value of t_encrypt_order.user_id
     *
     * @mbg.generated Mon Mar 30 09:45:06 CST 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_encrypt_order.user_id
     *
     * @param userId the value for t_encrypt_order.user_id
     *
     * @mbg.generated Mon Mar 30 09:45:06 CST 2020
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_encrypt_order.user_decrypt
     *
     * @return the value of t_encrypt_order.user_decrypt
     *
     * @mbg.generated Mon Mar 30 09:45:06 CST 2020
     */
    public String getUserDecrypt() {
        return userDecrypt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_encrypt_order.user_decrypt
     *
     * @param userDecrypt the value for t_encrypt_order.user_decrypt
     *
     * @mbg.generated Mon Mar 30 09:45:06 CST 2020
     */
    public void setUserDecrypt(String userDecrypt) {
        this.userDecrypt = userDecrypt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_encrypt_order.user_encrypt
     *
     * @return the value of t_encrypt_order.user_encrypt
     *
     * @mbg.generated Mon Mar 30 09:45:06 CST 2020
     */
    public String getUserEncrypt() {
        return userEncrypt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_encrypt_order.user_encrypt
     *
     * @param userEncrypt the value for t_encrypt_order.user_encrypt
     *
     * @mbg.generated Mon Mar 30 09:45:06 CST 2020
     */
    public void setUserEncrypt(String userEncrypt) {
        this.userEncrypt = userEncrypt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_encrypt_order.user_assisted
     *
     * @return the value of t_encrypt_order.user_assisted
     *
     * @mbg.generated Mon Mar 30 09:45:06 CST 2020
     */
    public String getUserAssisted() {
        return userAssisted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_encrypt_order.user_assisted
     *
     * @param userAssisted the value for t_encrypt_order.user_assisted
     *
     * @mbg.generated Mon Mar 30 09:45:06 CST 2020
     */
    public void setUserAssisted(String userAssisted) {
        this.userAssisted = userAssisted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_encrypt_order.created_time
     *
     * @return the value of t_encrypt_order.created_time
     *
     * @mbg.generated Mon Mar 30 09:45:06 CST 2020
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_encrypt_order.created_time
     *
     * @param createdTime the value for t_encrypt_order.created_time
     *
     * @mbg.generated Mon Mar 30 09:45:06 CST 2020
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_encrypt_order.update_time
     *
     * @return the value of t_encrypt_order.update_time
     *
     * @mbg.generated Mon Mar 30 09:45:06 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_encrypt_order.update_time
     *
     * @param updateTime the value for t_encrypt_order.update_time
     *
     * @mbg.generated Mon Mar 30 09:45:06 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_encrypt_order
     *
     * @mbg.generated Mon Mar 30 09:45:06 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TEncryptOrder other = (TEncryptOrder) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getUserDecrypt() == null ? other.getUserDecrypt() == null : this.getUserDecrypt().equals(other.getUserDecrypt()))
            && (this.getUserEncrypt() == null ? other.getUserEncrypt() == null : this.getUserEncrypt().equals(other.getUserEncrypt()))
            && (this.getUserAssisted() == null ? other.getUserAssisted() == null : this.getUserAssisted().equals(other.getUserAssisted()))
            && (this.getCreatedTime() == null ? other.getCreatedTime() == null : this.getCreatedTime().equals(other.getCreatedTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_encrypt_order
     *
     * @mbg.generated Mon Mar 30 09:45:06 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getUserDecrypt() == null) ? 0 : getUserDecrypt().hashCode());
        result = prime * result + ((getUserEncrypt() == null) ? 0 : getUserEncrypt().hashCode());
        result = prime * result + ((getUserAssisted() == null) ? 0 : getUserAssisted().hashCode());
        result = prime * result + ((getCreatedTime() == null) ? 0 : getCreatedTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }
}